### ISSUE TITLE
Sleepmode automatic turn-on based on user defined hours

### ISSUE THREAD

**Issue by Bucketsmith** [basnijholt/adaptive-lighting#306]
Aside from the upcoming RGB update for sleepmode, I would also request the ability to have the sleep mode automatically turn on during set hours.
I would love for it to engage AFTER the lights have been turned off by a user. Via lovelace, apps or via physical smart switches.
This way, it should only turn on into sleep mode AFTER the lights have gone off at least once after the set start time. Or if they stayed off when the automatic sleepmode started.
This would be useful for variable times of going to bed. So that it doesn't just hard-switch to low brightness, red light when I'm still busy downstairs. But once I've switched off lights myself, at any time after, it will automatically engage into sleepmode's RGB colour values.

**Comment by broyuken** [comment]
Do that with an automation

**Comment by Bucketsmith** [comment]
Can't. The Adaptive Lighting system will just revert it as per its own programming.

**Comment by broyuken** [comment]
Sleep mode doesn’t automatically turn on unless you do an automation. There is no programming for sleep mode.

**Comment by Bucketsmith** [comment]
Oh okay, you didn't understand. But that's okay, no one is perfect.
If you have an actual solution, don't be afraid to share!

**Comment by broyuken** [comment]
If you can help me understand the problem maybe I can help you with a solution. From my understanding what you’re asking can easily be handled by an automation.

**Comment by Bucketsmith** [comment]
Perhaps it can, but the only thing you've previously brought forward is "this works" instead of any actual solutions. It didn't seem right.
I've tried a simple automation but the problems I was facing was that I had no way for the system to tell to only go into this modified sleep mode AFTER the lights have already gone out once (after a set time). This is the key thing why I put up the request.
Yes, I can manually activate the modified sleep mode, but the entire point is to automate and create comfort.
The second issue is that the entire module is either RGBW OR white values. I didn't see any documentation to ONLY set the sleepmode with RGB values, and keep the daytime adaptive lighting in white values.
Third issue is then if I set any sort of automation to set the colour of the lights, adaptive lighting will just revert it back to white values as per its own programming, at the next interval that it normally does.
Sleepmode itself needs a way to be programmed to have RGB values seperately from the main adaptive system, for my plan to work.

**Comment by broyuken** [comment]
See now that you've actually explained what you want to do I can help you. It's a pretty simple automation you're trying to do. However the RGB thing I 100% agree with you on, and I'd love to see that fixed in a future version. To get around that you  have to have 2 integrations, one with RGB and one without, and trigger them off and on at certain times. Not worth it to set that up yet in my opinion. 

For your automation, why don't you just make the trigger when your "all lights" group is turned off with a condition that it's after sunset, or between whatever hours you want it to happen on. That way sleep mode would not take effect if any lights are on. 

Here's a super simple automation to use as a baseline.

```
alias: "Adaptive Lighting Sleep Mode"
trigger:
  - entity_id: group.all_lights
    from: "on"
    platform: state
    to: "off"
condition:
  - condition: time
    after: "20:00:00"
    before: "02:00:00"
action:
  - data: {}
    entity_id: group.adaptive_lights_sleep_mode
    service: switch.turn_on
mode: single
```

For your 3rd issue, this is exactly why the manual_control setting is there. Here's a simple automation to double click a light switch to turn a light blue.
```
alias: "👆🏻 Double Tap: Light to Blue"
description: ""
trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 15
      value: KeyPressed2x
condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == 'Scene 001' }}"
        sequence:
          - service: adaptive_lighting.set_manual_control
            data:
              entity_id: switch.adaptive_lighting_sengled_bulbs
              lights: light.test_light
              manual_control: true
          - service: light.turn_on
            data:
              color_name: homeassistant
              brightness_pct: 100
            target:
              entity_id: light.test_light
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.label == 'Scene 002' }}"
        sequence:
          - service: adaptive_lighting.set_manual_control
            data:
              entity_id: switch.adaptive_lighting_sengled_bulbs
              lights: light.test_light
              manual_control: false
	  default: []
mode: single
```

**Comment by Bucketsmith** [comment]
See, now that you've actually given a solution, I can work with that.
The problem still lies that either I would need to set up two instances of Adaptive Lighting, or with the vanilla automation, Adaptive Lighting is still just going to revert from the RGB value back to its own automated white value.

**Comment by broyuken** [comment]
Good luck with that bud

**Comment by basnijholt** [comment]
@Bucketsmith, maybe be a bit more friendly/grateful for the great help @broyuken is providing you?

**Comment by Bucketsmith** [comment]
@basnijholt He wasn't at first. :/ "Do that with an automation" was not a friendly reply at all to my OP. His follow-up was just as snarky. If you _give_ snarky, you _get_ snarky.
He was helpful later on and I've commended him for it. **I appreciate that part,** not how he started off.

I've already tried a similar approach but it doesn't work for my use-case, sadly.
@broyuken thanks for your eventual helpful suggestion, either way.
