### ISSUE TITLE
Take_over_control no longer working after 2024.3?

### ISSUE THREAD

**Issue by jhemak** [basnijholt/adaptive-lighting#954]
I have had no issues with this integration until 2024.3.  Now, when I manually change bulb settings the take_over_control feature does not seem to have an impact and AL reverts my manual changes after a few seconds.  Has anyone else experienced this problem?

**Comment by wgregorian** [comment]
+1, same behavior. 

Core 2024.3.3
Supervisor 2024.03.1
Operating System 12.1
Frontend 20240307.0

**Comment by langas6** [comment]
I seem to have a similar issue. Manual control either doesn't stay and reverts back to AL lighting mode, or won't come out of manual control back to AL

**Comment by jhemak** [comment]
@Arie6414 - what do you mean by manual reloading the specific configuration?

**Comment by Arie6414** [comment]
> @Arie6414 - what do you mean by manual reloading the specific configuration?

If you go to the integration, you will see your adaptieve lighting configurations… next to that you will have 3 dots on top of eachother (the option menu), there is a possibility to reload the configuration.

It looks like it does the Same as reloading your automations.

**Comment by jhemak** [comment]
Ah ok. I don’t think that is relevant to the problem I am having, but I know what you mean.

**Comment by Arie6414** [comment]
> Ah ok. I don’t think that is relevant to the problem I am having, but I know what you mean.

It could also be coincidence.. i also had the Same thing. And after reloading it did not occured anymore so far.
Something strange i found in the log as well, was that “take over” was not enabled. But in the UI i enabled it.

**Comment by langas6** [comment]
Seems the reloading is only a temp fix, works each time to get the lights right at that point in that instance, but then when it applies manual colour and brightness adjustments, either it doesn't work, or does and doesn't return back to AL mode again. Unless I do another reload

**Comment by basnijholt** [comment]
I am currently away from my home and somehow my HA server is down, so I have no means of testing anything at the moment.

I will be back at the end of the month. Will try to reproduce this then.

**Comment by langas6** [comment]
Not a problem, another thing I thought to try is recreate from scratch the different entries and initial testing has been positive. But only for one of the entities... Seems a bit hit and miss if it works and does what it says it's going to do, very very strange...

Thank you so much for looking into it! Loving the software a tonne! Just having a slight hickup 👍👍

**Comment by GollyJer** [comment]
AL has completely stopped working for me now. Removing and re-adding configurations was working for a while, but now nothing works to get the lights to adapt with 2024.4.x

**Comment by langas6** [comment]
Found a way to get around it with the automations, since the AL doesn't apply correctly when the lights turn on, you can set 3 extra actions after the "turn on" of the lights, set one to "turn off: switch" for the AL for the zone you have it set in (if you have multiple) then a 500ms "wait" action, then a "turn on: switch" for the same al, so you'll have a .5 second where it's the wrong colour/brightness, but it changes pretty quickly so it's still noticable, but at least it works again until it's 100% fixed and working. As i was having to do the reload 4-5-6 times a day to get the lights right, i now just have it that whenever the lights are turned on, the AL setting is reloaded and it's working fine now.

Just if anyone else could use this info for the time being

**Comment by langas6** [comment]
Hi all,
Thought i'd check in here to see if there was any movement :) Didn't want to push as i'm very appreciative of the software to start with, but thought i'd see how things were going on this one :)

**Comment by th3w1zard1** [comment]
anybody know the last version that worked? since i'm the one that fixed `take_over_control` last time, i might be best qualified to take a look at it.

**Comment by Arie6414** [comment]
I think it was 1.19.1

Met vriendelijke groet,

Arjen van de Belt
Verstuurd vanaf mijn IPhone

Op 14 mei 2024 om 04:42 heeft Benjamin Auquite ***@***.***> het volgende geschreven:

﻿

anybody know the last version that worked? since i'm the one that fixed take_over_control last time, i might be best qualified to take a look at it.

**Comment by langas6** [comment]
> anybody know the last version that worked? since i'm the one that fixed `take_over_control` last time, i might be best qualified to take a look at it.

Not 100%, but i'm on 2024.5.3 and it's not working, i think it might have been 2024.2 where it was working.

**Comment by jhemak** [comment]
I believe it worked through 2024.2.5.  It stopped working with 2024.3, and I assumed it had something to do with the significant performance improvements at startup that were introduced in that release.

**Comment by basnijholt** [comment]
I believe this is now fixed in 1.21.3.

**Comment by jhemak** [comment]
Sorry to say, not quite.  I am on 1.21.3 and still seeing the same problem.  Though I will add that the take over control does work intermittently --  in both this release and the last one.  So net/net, I'm seeing the same with 1.21.3 as I was with 1.21.2.

**Comment by jhemak** [comment]
Continuing to see the same problem in 1.22.0

**Comment by tpsherratt** [comment]
I too am still seeing this issue on 1.22.0

**Comment by wise-rice** [comment]
+1

**Comment by basnijholt** [comment]
I really cannot reproduce the issue. All is working fine for me at my home.

**Comment by basnijholt** [comment]
Without logs that show what happens there is no way for me to solve this.

**Comment by casimcdaniels** [comment]
Issue present on 1.22.

Core 2024.7.2
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240710.0

There are no logs reported even with debug mode on.

**Comment by Autoparallel** [comment]
Also finding a similar issue I believe. 

Anyway I can help get some logs to debug, I would. 

One example I have is a light that I call light.turn_off with a transition of 120s while my adaptive refresh is 60s. This light will never make it more than halfway off since it gets re-adapted when it should have taken over its own control as far as I understand.

**Comment by thecastle20** [comment]
It's got worse- after the HA 2024.7.4 update they now only adapt at service start/reload. It's as if the adapt once switch is checked (though it's not).

**Comment by tmikoss** [comment]
I might have some input - it seems that this issue happens only to lights that have not been touched via HA UI.

I have bunch of lights that only ever get dimmed with the physical switch (connected to Shelly Dimmer 2). And they would constantly adapt after manual control. No changing of settings helped. However, after updating one light via HA UI, it started staying put. 

As in, modify with HA, turn off with switch, turn on with switch, observe brightness being adapted, modify brightness with switch, observe it staying on.

I have three lights in one AL group - "fixed" one of them this way, observed the others adapting again after brightness modification with switch, was able to "fix" the others too, without touching any AL settings.

Is it possible you rely on some initial value in manual change detection, that only gets populated from HA-initiated updates?

First noticed the issue with 2024.3 / 1.20, updated to 2024.7 / 1.22, stumbled upon the "fix" in the updated version. Will observe if the "fix" persists.

**Comment by wise-rice** [comment]
detect_non_ha_changes is broken. Adaptive Lighting cannot recognize the external changes anymore.

If I adapt lights outside of Home Assistant (e.g. using a TUYA zigbee Dimmer) the lights will be adapted a few seconds later, again. Manual changes are therefore impossible (unless made through HomeAssistant).

I use zigbee2mqtt groups for my lights. The problem also occurs for an individual light without group.

detect_non_ha_changes did not work for a few months. Also not in the latest two releases of HomeAssistant Core,  Zigbee2MQTT, Operating System and/or Adaptive Lighting.

Currently I am using:
Adaptive Lighting: 1.22
Core: 2024.8.1
Supervisor: 2024.08.0
Operating System: 13.0
Frontend: 20240809.0

Please let me know how I can help you (w.g. how to provide the necessary logs, if possible)

**Comment by trrevvorr** [comment]
I'm experiencing the same issue where `detect_non_ha_changes` is unreliable. Sometimes it detects changes made outside HA, other times it does not. I took a screen recording where I adjusted the brightness of my lights outside of HA (via the Lutron app) then waited for the next update of AL. The first time, AL correctly detected the change. The second time it did not.

Screen recording: https://drive.google.com/file/d/13VLluB9DC9JugWljQvmoGFw7bjhttg32/view?usp=sharing

**Comment by Autoparallel** [comment]
> I'm experiencing the same issue where `detect_non_ha_changes` is unreliable. Sometimes it detects changes made outside HA, other times it does not. I took a screen recording where I adjusted the brightness of my lights outside of HA (via the Lutron app) then waited for the next update of AL. The first time, AL correctly detected the change. The second time it did not.
> 
> Screen recording: https://drive.google.com/file/d/13VLluB9DC9JugWljQvmoGFw7bjhttg32/view?usp=sharing

Yeah, I have some reliable uses of it with my Lutron devices but their state changes are different than others. E.g., when you transition a light on, it will jump to that brightness instantly and the transition is handled on Lutron's side. This has allowed my "transition off" actions to work.

Other lights such as Nanoleaf or Lifx are not working at all in this regard.

**Comment by MrMuetze** [comment]
I think I am encountering this issue right now as well. `take_over_control` does not seem to be working anymore. Here are some logs:

```
2024-10-03 00:20:27.575 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Sleeping Room: '_update_attrs_and_maybe_adapt_lights' called with context.id='01J97N40HQ:al:KNWG:ntrv:0X' lights: 'None', transition: '45.0', force: 'False'
2024-10-03 00:20:27.581 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Sleeping Room: filtered_lights: '[]'
2024-10-03 00:20:30.908 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected an 'light.turn_on('['light.werkbank']')' event with context.id='01J97N43SV30P73DQ6ZC6RR5PR'
2024-10-03 00:20:30.909 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] (0) _service_interceptor_turn_on_handler: call.context.id='01J97N43SV30P73DQ6ZC6RR5PR', is_skipped_hash='False'
2024-10-03 00:20:30.909 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] (1) _service_interceptor_turn_on_handler: call='<ServiceCall light.turn_on (c:01J97N43SV30P73DQ6ZC6RR5PR): entity_id=['light.werkbank'], params=brightness=189>', service_data='{'entity_id': ['light.werkbank'], 'params': {'brightness': 189}}'
2024-10-03 00:20:30.910 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] No switch found for entity_id='light.werkbank', skipped='['light.werkbank']'
2024-10-03 00:20:30.910 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] (2) _service_interceptor_turn_on_handler: switch_to_eids='{}', skipped='['light.werkbank']'
2024-10-03 00:20:31.152 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected a 'light.werkbank' 'state_changed' event: '{'effect_list': ['None', 'candle'], 'supported_color_modes': [<ColorMode.BRIGHTNESS: 'brightness'>], 'effect': 'None', 'color_mode': <ColorMode.BRIGHTNESS: 'brightness'>, 'brightness': 189, 'mode': 'normal', 'dynamics': 'none', 'friendly_name': 'Werkbank', 'supported_features': <LightEntityFeature.EFFECT|FLASH|TRANSITION: 44>}' with context.id='01J97N43SV30P73DQ6ZC6RR5PR'
2024-10-03 00:20:31.154 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected a 'light.home_office' 'state_changed' event: '{'min_color_temp_kelvin': 2202, 'max_color_temp_kelvin': 4000, 'min_mireds': 250, 'max_mireds': 454, 'supported_color_modes': [<ColorMode.COLOR_TEMP: 'color_temp'>], 'color_mode': <ColorMode.COLOR_TEMP: 'color_temp'>, 'brightness': 106, 'color_temp_kelvin': 2500, 'color_temp': 400, 'hs_color': (28.874, 72.522), 'rgb_color': (255, 159, 70), 'xy_color': (0.546, 0.389), 'is_hue_group': True, 'hue_scenes': {'Hell', 'Entspannen', 'Konzentrieren', 'Lesen', 'Energie tanken', 'Gedimmt', 'Nachtlicht'}, 'hue_type': 'room', 'lights': {'Stehlampe 1', 'Werkbank', 'Stehlampe 2', 'Stehlampe 3'}, 'entity_id': {'light.color_temperature_light_1_2', 'light.werkbank', 'light.color_temperature_light_2', 'light.color_temperature_light_1_3'}, 'dynamics': False, 'icon': 'mdi:lightbulb-group', 'friendly_name': 'Home Office', 'supported_features': <LightEntityFeature.FLASH|TRANSITION: 40>}' with context.id='01J97N441JD2CV63NJK3E9PS81'
2024-10-03 00:21:17.234 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Adaptive Lighting: '_update_attrs_and_maybe_adapt_lights' called with context.id='01J97N5H1H:al:IFSG:ntrv:04' lights: 'None', transition: '45.0', force: 'False'
2024-10-03 00:21:17.241 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Adaptive Lighting: filtered_lights: '['light.home_office']'
2024-10-03 00:21:17.241 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] is_proactively_adapting_context='False', context_id='01J97N2RF5:al:IFSG:ntrv:03'
2024-10-03 00:21:17.242 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Adaptive Lighting: Calling _adapt_light from _update_attrs_and_maybe_adapt_lights: 'light.home_office' with transition 45.0 and context.id=01J97N5H1H:al:IFSG:ntrv:04
2024-10-03 00:21:17.247 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Adaptive Lighting: Setting color_temp of light light.home_office
2024-10-03 00:21:17.248 DEBUG (MainThread) [custom_components.adaptive_lighting.adaptation_utils] Preparing adaptation data for light.home_office with service data {'entity_id': 'light.home_office', 'transition': 45.0, 'brightness': 78, 'color_temp_kelvin': 2500}
2024-10-03 00:21:17.248 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Adaptive Lighting: execute_cancellable_adaptation_calls with data: AdaptationData(entity_id=light.home_office, context_id=01J97N5H1H:al:IFSG:ntrv:04, sleep_time=22.7, force=False, max_length=2, which=both, initial_sleep=False)
2024-10-03 00:21:17.248 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Adaptive Lighting: Scheduling 'light.turn_on' with the following 'service_data': {'entity_id': 'light.home_office', 'brightness': 78, 'transition': 22.5} with context.id='01J97N5H1H:al:IFSG:ntrv:04'
2024-10-03 00:21:17.249 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected an 'light.turn_on('['light.home_office']')' event with context.id='01J97N5H1H:al:IFSG:ntrv:04'
2024-10-03 00:21:17.249 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] (0) _service_interceptor_turn_on_handler: call.context.id='01J97N5H1H:al:IFSG:ntrv:04', is_skipped_hash='False'
2024-10-03 00:21:17.447 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected a 'light.werkbank' 'state_changed' event: '{'effect_list': ['None', 'candle'], 'supported_color_modes': [<ColorMode.BRIGHTNESS: 'brightness'>], 'effect': 'None', 'color_mode': <ColorMode.BRIGHTNESS: 'brightness'>, 'brightness': 78, 'mode': 'normal', 'dynamics': 'none', 'friendly_name': 'Werkbank', 'supported_features': <LightEntityFeature.EFFECT|FLASH|TRANSITION: 44>}' with context.id='01J97N5H87TW3V78AD85JD8C1P'
2024-10-03 00:21:17.449 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected a 'light.home_office' 'state_changed' event: '{'min_color_temp_kelvin': 2202, 'max_color_temp_kelvin': 4000, 'min_mireds': 250, 'max_mireds': 454, 'supported_color_modes': [<ColorMode.COLOR_TEMP: 'color_temp'>], 'color_mode': <ColorMode.COLOR_TEMP: 'color_temp'>, 'brightness': 78, 'color_temp_kelvin': 2500, 'color_temp': 400, 'hs_color': (28.874, 72.522), 'rgb_color': (255, 159, 70), 'xy_color': (0.546, 0.389), 'is_hue_group': True, 'hue_scenes': {'Hell', 'Entspannen', 'Konzentrieren', 'Lesen', 'Energie tanken', 'Gedimmt', 'Nachtlicht'}, 'hue_type': 'room', 'lights': {'Stehlampe 1', 'Werkbank', 'Stehlampe 2', 'Stehlampe 3'}, 'entity_id': {'light.color_temperature_light_1_2', 'light.werkbank', 'light.color_temperature_light_2', 'light.color_temperature_light_1_3'}, 'dynamics': False, 'icon': 'mdi:lightbulb-group', 'friendly_name': 'Home Office', 'supported_features': <LightEntityFeature.FLASH|TRANSITION: 40>}' with context.id='01J97N5H1H:al:IFSG:ntrv:04'
2024-10-03 00:21:17.449 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] AdaptiveLightingManager: New adapt '<state light.home_office=on; min_color_temp_kelvin=2202, max_color_temp_kelvin=4000, min_mireds=250, max_mireds=454, supported_color_modes=[<ColorMode.COLOR_TEMP: 'color_temp'>], color_mode=color_temp, brightness=78, color_temp_kelvin=2500, color_temp=400, hs_color=(28.874, 72.522), rgb_color=(255, 159, 70), xy_color=(0.546, 0.389), is_hue_group=True, hue_scenes={'Hell', 'Entspannen', 'Konzentrieren', 'Lesen', 'Energie tanken', 'Gedimmt', 'Nachtlicht'}, hue_type=room, lights={'Stehlampe 1', 'Werkbank', 'Stehlampe 2', 'Stehlampe 3'}, entity_id={'light.color_temperature_light_1_2', 'light.werkbank', 'light.color_temperature_light_2', 'light.color_temperature_light_1_3'}, dynamics=False, icon=mdi:lightbulb-group, friendly_name=Home Office, supported_features=40 @ 2024-10-03T00:00:03.776749+02:00>' found for light.home_office
2024-10-03 00:21:17.457 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Start transition timer of 22.5 seconds for light light.home_office
2024-10-03 00:21:26.912 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected a 'light.werkbank' 'state_changed' event: '{'effect_list': ['None', 'candle'], 'supported_color_modes': [<ColorMode.BRIGHTNESS: 'brightness'>], 'effect': 'None', 'color_mode': <ColorMode.BRIGHTNESS: 'brightness'>, 'brightness': 146, 'mode': 'normal', 'dynamics': 'none', 'friendly_name': 'Werkbank', 'supported_features': <LightEntityFeature.EFFECT|FLASH|TRANSITION: 44>}' with context.id='01J97N5TG0GMK2DFH9FWMEM8V8'
2024-10-03 00:21:26.914 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected a 'light.home_office' 'state_changed' event: '{'min_color_temp_kelvin': 2202, 'max_color_temp_kelvin': 4000, 'min_mireds': 250, 'max_mireds': 454, 'supported_color_modes': [<ColorMode.COLOR_TEMP: 'color_temp'>], 'color_mode': <ColorMode.COLOR_TEMP: 'color_temp'>, 'brightness': 95, 'color_temp_kelvin': 2500, 'color_temp': 400, 'hs_color': (28.874, 72.522), 'rgb_color': (255, 159, 70), 'xy_color': (0.546, 0.389), 'is_hue_group': True, 'hue_scenes': {'Hell', 'Entspannen', 'Konzentrieren', 'Lesen', 'Energie tanken', 'Gedimmt', 'Nachtlicht'}, 'hue_type': 'room', 'lights': {'Stehlampe 1', 'Werkbank', 'Stehlampe 2', 'Stehlampe 3'}, 'entity_id': {'light.color_temperature_light_1_2', 'light.werkbank', 'light.color_temperature_light_2', 'light.color_temperature_light_1_3'}, 'dynamics': False, 'icon': 'mdi:lightbulb-group', 'friendly_name': 'Home Office', 'supported_features': <LightEntityFeature.FLASH|TRANSITION: 40>}' with context.id='01J97N5TG26XR9DZ5EEW693THQ'
2024-10-03 00:21:38.399 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected a 'light.werkbank' 'state_changed' event: '{'effect_list': ['None', 'candle'], 'supported_color_modes': [<ColorMode.BRIGHTNESS: 'brightness'>], 'effect': 'None', 'color_mode': <ColorMode.BRIGHTNESS: 'brightness'>, 'brightness': 89, 'mode': 'normal', 'dynamics': 'none', 'friendly_name': 'Werkbank', 'supported_features': <LightEntityFeature.EFFECT|FLASH|TRANSITION: 44>}' with context.id='01J97N65PYXVH1CQP0FXKZT8F3'
2024-10-03 00:21:38.401 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected a 'light.home_office' 'state_changed' event: '{'min_color_temp_kelvin': 2202, 'max_color_temp_kelvin': 4000, 'min_mireds': 250, 'max_mireds': 454, 'supported_color_modes': [<ColorMode.COLOR_TEMP: 'color_temp'>], 'color_mode': <ColorMode.COLOR_TEMP: 'color_temp'>, 'brightness': 80, 'color_temp_kelvin': 2500, 'color_temp': 400, 'hs_color': (28.874, 72.522), 'rgb_color': (255, 159, 70), 'xy_color': (0.546, 0.389), 'is_hue_group': True, 'hue_scenes': {'Hell', 'Entspannen', 'Konzentrieren', 'Lesen', 'Energie tanken', 'Gedimmt', 'Nachtlicht'}, 'hue_type': 'room', 'lights': {'Stehlampe 1', 'Werkbank', 'Stehlampe 2', 'Stehlampe 3'}, 'entity_id': {'light.color_temperature_light_1_2', 'light.werkbank', 'light.color_temperature_light_2', 'light.color_temperature_light_1_3'}, 'dynamics': False, 'icon': 'mdi:lightbulb-group', 'friendly_name': 'Home Office', 'supported_features': <LightEntityFeature.FLASH|TRANSITION: 40>}' with context.id='01J97N65Q1YGY4N4GK09DS1MCP'
2024-10-03 00:21:39.955 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Adaptive Lighting: Scheduling 'light.turn_on' with the following 'service_data': {'entity_id': 'light.home_office', 'color_temp_kelvin': 2500, 'transition': 22.5} with context.id='01J97N5H1H:al:IFSG:ntrv:04'
2024-10-03 00:21:39.956 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected an 'light.turn_on('['light.home_office']')' event with context.id='01J97N5H1H:al:IFSG:ntrv:04'
2024-10-03 00:21:39.956 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] (0) _service_interceptor_turn_on_handler: call.context.id='01J97N5H1H:al:IFSG:ntrv:04', is_skipped_hash='False'
2024-10-03 00:21:39.963 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Transition finished for light light.home_office
2024-10-03 00:21:49.964 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected a 'light.werkbank' 'state_changed' event: '{'effect_list': ['None', 'candle'], 'supported_color_modes': [<ColorMode.BRIGHTNESS: 'brightness'>], 'effect': 'None', 'color_mode': <ColorMode.BRIGHTNESS: 'brightness'>, 'brightness': 78, 'mode': 'normal', 'dynamics': 'none', 'friendly_name': 'Werkbank', 'supported_features': <LightEntityFeature.EFFECT|FLASH|TRANSITION: 44>}' with context.id='01J97N6H0BWB13NM8XM4NHAS8Q'
2024-10-03 00:21:49.965 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected a 'light.home_office' 'state_changed' event: '{'min_color_temp_kelvin': 2202, 'max_color_temp_kelvin': 4000, 'min_mireds': 250, 'max_mireds': 454, 'supported_color_modes': [<ColorMode.COLOR_TEMP: 'color_temp'>], 'color_mode': <ColorMode.COLOR_TEMP: 'color_temp'>, 'brightness': 78, 'color_temp_kelvin': 2500, 'color_temp': 400, 'hs_color': (28.874, 72.522), 'rgb_color': (255, 159, 70), 'xy_color': (0.546, 0.389), 'is_hue_group': True, 'hue_scenes': {'Hell', 'Entspannen', 'Konzentrieren', 'Lesen', 'Energie tanken', 'Gedimmt', 'Nachtlicht'}, 'hue_type': 'room', 'lights': {'Stehlampe 1', 'Werkbank', 'Stehlampe 2', 'Stehlampe 3'}, 'entity_id': {'light.color_temperature_light_1_2', 'light.werkbank', 'light.color_temperature_light_2', 'light.color_temperature_light_1_3'}, 'dynamics': False, 'icon': 'mdi:lightbulb-group', 'friendly_name': 'Home Office', 'supported_features': <LightEntityFeature.FLASH|TRANSITION: 40>}' with context.id='01J97N6H0DQEAHRV9TCJWZ7TAY'
```

`light.werkbank` is in the `light.home_office` group. Configuration is mostly default, with `take_over_control` enabled. I've tried adding the Hue group (`light.home_office`) or the individual lights (like `light.werkbank`) to the integration, but nothing seems to work.

The logs seem to confirm that an event changing the brightness was registered, but it did not lead to the integration stopping the adaption there. Not sure if that is related to the latest Home Assistant update. I am on

Core 2024.10.0
Supervisor 2024.09.1
Operating System 13.1
Frontend 20241002.2

Starting a custom transition with brightness, duration and color temperature seems to work fine as long as `adapt_only_on_bare_turn_on` is activated. But this is not the situation that I've explained above.

If there is anything else I can provide to debug this, just let me know. Also my issue is not related to `detect_non_ha_changes` (I think). I have never enabled that option before.

**Comment by bjornarfjelldal** [comment]
Same issue here for many months. Does not work with most of my Hue / ZigBee-lights, however works better with Fibaro Dimmer 2 Z-wave-devices.

Normal scenario is when using homekit/Siri to say "set lights in living room to 20%", all four lights goes down to 20%, however only two of them remain, whereas the other two (Hue/ZigBee) increases back to previous state in a matter of seconds. Need to manually set them in the UI (some times more than once) for them to stick..

**Comment by jhemak** [comment]
I have found that my problem, which was the original reason for this issue, was caused by a motion sensor issuing a `light.turn_on` command to my lamp, which had already been on and under manual control.  For some reason this occasionally caused the light to re-adapt.  I updated my automation to only trigger the `light.turn_on` if the light is currently off.  This seems to have resolved the problem I was having.

**Comment by barney34** [comment]
> I'm experiencing the same issue where `detect_non_ha_changes` is unreliable. Sometimes it detects changes made outside HA, other times it does not. I took a screen recording where I adjusted the brightness of my lights outside of HA (via the Lutron app) then waited for the next update of AL. The first time, AL correctly detected the change. The second time it did not.
> 
> Screen recording: https://drive.google.com/file/d/13VLluB9DC9JugWljQvmoGFw7bjhttg32/view?usp=sharing

I think this has to do with the inital reading of the light brightness isnt taken until the first adaptation but I'm not sure.  So if you wait "Frequency to adapt the lights, in seconds" time and then adapt does it work?

**Comment by barney34** [comment]
@trrevvorr ok my issue is a little different.   On initial turn on and physical adapting results in AL re-adapting.   But almost always the second physical adaption will move the light into manual mode.   So I wrote this automation and it works just about every time unless I physically adapt within a second of light coming one which is faster then the light can register with HA.    


`: Pantry Test
description: ""
triggers:
  - trigger: state
    entity_id:
      - light.pantry
    attribute: brightness
conditions:
  - condition: or
    conditions:
      - condition: template
        value_template: >-
          {{ (trigger.from_state.attributes.brightness | float -
          trigger.to_state.attributes.brightness | float) > (7 / 100 * 255) }}
      - condition: template
        value_template: >-
          {{ (trigger.to_state.attributes.brightness | float -
          trigger.from_state.attributes.brightness | float) > (7 / 100 * 255) }}
actions:
  - action: adaptive_lighting.set_manual_control
    data:
      manual_control: true
      entity_id: switch.adaptive_lighting_rush
      lights:
        - light.pantry
`

**Comment by milch** [comment]
I had the same problem on my Lutron lights (others work fine). Fixed it with these automations: 

```
  - id: lutron_al_physical_manual
    alias: "Lutron AL: set manual on physical switch"
    description: >-
      When any Lutron light is physically turned on, set adaptive lighting
      to manual control so it doesn't override the brightness.
    triggers:
    - trigger: state
      entity_id:
      # list of lights here
      from: 'off'
      to: 'on'
    conditions:
    - condition: template
      value_template: >-
        {{ trigger.to_state.context.user_id is none
           and trigger.to_state.context.parent_id is none }}
    actions:
    - condition: template
      value_template: >-
        {{ trigger.entity_id not in
           states('input_text.lutron_al_svc_call_entities').split(',') }}
    - action: adaptive_lighting.set_manual_control
      data:
        entity_id: switch.lutron_lights_adaptive_lighting_lutron_lights
        lights: "{{ trigger.entity_id }}"
        manual_control: true
    mode: parallel

  - id: lutron_al_resume_service_call
    alias: "Lutron AL: resume on bare service call"
    description: >-
      When turning on a Lutron light without specifying brightness,
      resume adaptive lighting. 
    triggers:
    - trigger: event
      event_type: call_service
      event_data:
        domain: light
        service: turn_on
    conditions:
    - condition: template
      value_template: >-
        {% set svc = trigger.event.data.get('service_data', {}) %}
        {% set lutron_lights = expand('group.lutron_lights')
           | map(attribute='entity_id') | list %}
        {% set target = svc.get('entity_id', []) %}
        {% set target_list = [target] if target is string else target %}
        {% set manual_keys = ['brightness', 'brightness_pct',
           'brightness_step', 'brightness_step_pct'] %}
        {{ trigger.event.context.user_id is none
           and target_list | select('in', lutron_lights) | list | count > 0
           and manual_keys | select('in', svc) | list | count == 0 }}
    actions:
    - variables:
        svc: "{{ trigger.event.data.get('service_data', {}) }}"
        target: "{{ svc.get('entity_id', []) }}"
        target_list: "{{ [target] if target is string else target }}"
    - action: input_text.set_value
      target:
        entity_id: input_text.lutron_al_svc_call_entities
      data:
        value: >-
          {{ (states('input_text.lutron_al_svc_call_entities') ~ ',' ~ target_list | join(','))
             | regex_replace('^,', '') }}
    - action: adaptive_lighting.set_manual_control
      data:
        entity_id: switch.lutron_lights_adaptive_lighting_lutron_lights
        lights: "{{ target_list }}"
        manual_control: false
    - delay:
        seconds: 1
    - action: input_text.set_value
      target:
        entity_id: input_text.lutron_al_svc_call_entities
      data:
        value: >-
          {% set current = states('input_text.lutron_al_svc_call_entities').split(',') %}
          {% set remove = target_list %}
          {{ current | reject('in', remove) | reject('eq', '') | join(',') }}
    mode: parallel
```

Uses a helper group with all the lights and an input_text. Basically this handles the cases I care about: 

1. Bare turn on via switch
2. Bare turn on via home assistant
3. Bare turn on via HomeKit / Siri (voice assistant) 

It was especially annoying because the Diva dimmers I use have a paddle to control the dim level, and often if you turned it on and changed the paddle immediately, AL would revert it a second later

**Comment by basnijholt** [comment]
This thread contains several different cases:

- Repeated automation turn-ons: the original reporter found this cause, and #1583 now covers it.
- Physical turn-ons that should stay manual: v1.32.0 adds `manual_control_on_external_turn_on`. This does not make a later bare turn-on resume an already-on light.
- Long off-transitions: investigating these under #1069.
- Shelly/Lutron dimming while already on: the general sequence passed locally, including two physical power cycles without an external HA turn-on. That does not verify those devices.

For the remaining case, please share v1.32.0 diagnostics and debug logs covering the physical dim and the unwanted readaptation. Keeping this open for that evidence.
